staffs = [
    {
        "id": "s1",
        "name": "Linh Phan",
        "role": "Senior Nail Artist",
        "bio": "10+ years crafting Gel-X and hand-painted designs. Friendly, detail-obsessed, and great with custom sets.",
        "bio_vi": "Hơn 10 năm kinh nghiệm Gel-X và vẽ tay tỉ mỉ. Tư vấn nhiệt tình, chuyên set thiết kế theo yêu cầu.",
        "languages": ["vi", "en"],
        "specialties": ["Gel-X", "Hand-painted art", "Ombré", "Builder Gel Overlay"],
        "can_do_services": [
            "svc-gelx", "svc-gel-mani", "svc-builder-overlay",
            "add-full-art", "add-french", "svc-gel-removal",
            "svc-classic-mani", "svc-polish-change-hands"
        ],
        "years_experience": 10,
        "rating": 4.9,
        "seniority": "senior",
        "price_multiplier": 1.20,
        "aliases": ["Linh", "chị Linh"],
        "image_url": None
    },
    {
        "id": "s2",
        "name": "Minh Anh",
        "role": "Gel Color Specialist",
        "bio": "Known for flawless gel color application and long-lasting shine. Minimalist to bold palettes.",
        "bio_vi": "Chuyên gia sơn gel bền đẹp, lên màu chuẩn từ tối giản đến nổi bật.",
        "languages": ["vi", "en"],
        "specialties": ["Gel Color", "French Tips", "Quick-dry Top"],
        "can_do_services": [
            "svc-gel-mani", "svc-gel-pedi", "add-french",
            "svc-gel-removal", "svc-classic-mani", "svc-classic-pedi"
        ],
        "years_experience": 6,
        "rating": 4.8,
        "seniority": "mid",
        "price_multiplier": 1.10,
        "aliases": ["Minh Anh"],
        "image_url": None
    },
    {
        "id": "s3",
        "name": "Hà My",
        "role": "Nail Artist",
        "bio": "Delicate linework and cute decals. Great for K-beauty inspired sets and short nails.",
        "bio_vi": "Vẽ nét mảnh, decal xinh, hợp style Hàn và móng ngắn.",
        "languages": ["vi", "en"],
        "specialties": ["Simple Art", "Full-set Art", "K-style"],
        "can_do_services": [
            "add-simple-art", "add-full-art", "svc-classic-mani",
            "svc-polish-change-hands", "svc-kids-mani", "svc-gel-mani"
        ],
        "years_experience": 4,
        "rating": 4.7,
        "seniority": "mid",
        "price_multiplier": 1.05,
        "aliases": ["Hamy", "Hà-My"],
        "image_url": None
    },
    {
        "id": "s4",
        "name": "Quang Dũng",
        "role": "Spa Pedicure Technician",
        "bio": "Gentle, hygienic spa pedicures with careful callus care. Customer-first, relaxing experience.",
        "bio_vi": "Chăm sóc chân kỹ, vệ sinh chuẩn, mài gót nhẹ nhàng – trải nghiệm thư giãn.",
        "languages": ["vi", "en"],
        "specialties": ["Spa Pedicure", "Callus Care", "Paraffin"],
        "can_do_services": [
            "svc-classic-pedi", "svc-gel-pedi", "add-callus",
            "add-paraffin", "svc-polish-change-toes", "svc-gel-removal"
        ],
        "years_experience": 7,
        "rating": 4.8,
        "seniority": "senior",
        "price_multiplier": 1.15,
        "aliases": ["Dũng"],
        "image_url": None
    },
    {
        "id": "s5",
        "name": "Thu Trang",
        "role": "Acrylic Master",
        "bio": "Sculpted acrylics with durable shape and balance. Loves modern square and almond forms.",
        "bio_vi": "Chuyên đắp bột form chuẩn, bền đẹp; yêu thích dáng vuông và almond hiện đại.",
        "languages": ["vi", "en"],
        "specialties": ["Acrylic Full Set", "Acrylic Refill", "Sculpting"],
        "can_do_services": [
            "svc-acrylic-full", "svc-acrylic-refill", "svc-acrylic-removal",
            "add-full-art", "add-french", "svc-polish-change-hands"
        ],
        "years_experience": 8,
        "rating": 4.85,
        "seniority": "senior",
        "price_multiplier": 1.20,
        "aliases": ["Trang"],
        "image_url": None
    },
    {
        "id": "s6",
        "name": "Kim Chi",
        "role": "Junior Technician",
        "bio": "Fast and neat polish changes; great with kids’ services and simple gel sets.",
        "bio_vi": "Đổi sơn nhanh gọn, làm dịch vụ trẻ em và gel đơn giản tốt.",
        "languages": ["vi", "en"],
        "specialties": ["Polish Change", "Kids Manicure", "Basic Gel"],
        "can_do_services": [
            "svc-polish-change-hands", "svc-polish-change-toes",
            "svc-kids-mani", "svc-classic-mani", "svc-gel-mani"
        ],
        "years_experience": 2,
        "rating": 4.6,
        "seniority": "junior",
        "price_multiplier": 0.95,
        "aliases": ["Chi"],
        "image_url": None
    },
]

services = [
    # --- Services: Manicure/Pedicure ---
    {"id": "svc-classic-mani", "name": "Classic Manicure", "price": 120000,
        "type": "service", "category": "Manicure", "duration_min": 30,
        "aliases": ["basic manicure", "cắt da sơn thường"]},
    {"id": "svc-classic-pedi", "name": "Classic Pedicure", "price": 180000,
        "type": "service", "category": "Pedicure", "duration_min": 40,
        "aliases": ["basic pedicure", "cắt da chân sơn thường"]},
    {"id": "svc-gel-mani", "name": "Gel Manicure", "price": 280000,
        "type": "service", "category": "Gel", "duration_min": 50,
        "aliases": ["shellac", "sơn gel tay"]},
    {"id": "svc-gel-pedi", "name": "Gel Pedicure", "price": 380000,
        "type": "service", "category": "Gel", "duration_min": 60,
        "aliases": ["gel toes", "sơn gel chân"]},
    {"id": "svc-acrylic-full", "name": "Acrylic Full Set", "price": 450000,
        "type": "service", "category": "Extensions", "duration_min": 90,
        "aliases": ["nối móng bột full set"]},
    {"id": "svc-acrylic-refill", "name": "Acrylic Refill", "price": 300000,
        "type": "service", "category": "Extensions", "duration_min": 70,
        "aliases": ["đắp bột dặm", "fill"]},
    {"id": "svc-gelx", "name": "Gel-X Soft Gel Extensions", "price": 650000,
        "type": "service", "category": "Extensions", "duration_min": 95,
        "aliases": ["aprés", "nối móng gel"]},
    {"id": "svc-builder-overlay", "name": "Builder Gel Overlay", "price": 400000,
        "type": "service", "category": "Gel", "duration_min": 70,
        "aliases": ["hard gel overlay", "gel cứng phủ móng"]},

    # --- Add-ons ---
    {"id": "add-french", "name": "French Tips (add-on)", "price": 60000,
        "type": "service", "category": "Add-on", "duration_min": 10,
        "aliases": ["french", "đầu móng trắng"], "is_addon": True},
    {"id": "add-simple-art", "name": "Nail Art – Simple (2–4 nails)", "price": 50000,
        "type": "service", "category": "Add-on", "duration_min": 15,
        "aliases": ["nail art đơn giản"], "is_addon": True},
    {"id": "add-full-art", "name": "Nail Art – Full Set", "price": 150000,
        "type": "service", "category": "Add-on", "duration_min": 35,
        "aliases": ["nail art phức tạp"], "is_addon": True},
    {"id": "add-paraffin", "name": "Paraffin Treatment", "price": 90000,
        "type": "service", "category": "Spa", "duration_min": 15,
        "aliases": ["wax paraffin", "dưỡng ấm"]},
    {"id": "add-callus", "name": "Callus Treatment", "price": 70000,
        "type": "service", "category": "Spa", "duration_min": 15,
        "aliases": ["mài gót", "chăm sóc gót"]},

    # --- Removals / Quick fixes ---
    {"id": "svc-gel-removal", "name": "Gel Removal", "price": 50000,
        "type": "service", "category": "Removal", "duration_min": 15,
        "aliases": ["tháo gel"]},
    {"id": "svc-acrylic-removal", "name": "Acrylic Removal", "price": 80000,
        "type": "service", "category": "Removal", "duration_min": 25,
        "aliases": ["tháo bột"]},
    {"id": "svc-polish-change-hands", "name": "Polish Change – Hands", "price": 60000,
        "type": "service", "category": "Polish", "duration_min": 15,
        "aliases": ["đổi sơn tay"]},
    {"id": "svc-polish-change-toes", "name": "Polish Change – Toes", "price": 70000,
        "type": "service", "category": "Polish", "duration_min": 15,
        "aliases": ["đổi sơn chân"]},
    {"id": "svc-kids-mani", "name": "Kids Manicure", "price": 80000,
        "type": "service", "category": "Kids", "duration_min": 20,
        "aliases": ["manicure trẻ em"]},

    # --- Retail products for upsell ---
    {"id": "ret-cuticle-oil", "name": "Cuticle Oil (15ml)", "price": 99000,
        "type": "retail", "category": "Retail", "aliases": ["dầu dưỡng kẽ móng"]},
    {"id": "ret-hand-cream", "name": "Hand Cream – Shea", "price": 129000,
        "type": "retail", "category": "Retail", "aliases": ["kem dưỡng tay"]},
    {"id": "ret-base-coat", "name": "Nail Strengthener Base Coat", "price": 149000,
        "type": "retail", "category": "Retail", "aliases": ["sơn lót dưỡng"]},
    {"id": "ret-top-coat", "name": "Quick-Dry Top Coat", "price": 149000,
        "type": "retail", "category": "Retail", "aliases": ["sơn bóng nhanh khô"]},
    {"id": "ret-remover", "name": "Acetone-Free Polish Remover", "price": 79000,
        "type": "retail", "category": "Retail", "aliases": ["nước tẩy sơn không acetone"]},
]
