"""Add working hour to salon

Revision ID: 39be446c5be7
Revises: b4c3d3327993
Create Date: 2025-10-27 10:52:56.436377

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '39be446c5be7'
down_revision = 'b4c3d3327993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salon_services')
    op.add_column('salons', sa.Column('start_working_time', sa.Time(), nullable=True))
    op.add_column('salons', sa.Column('end_working_time', sa.Time(), nullable=True))
    op.drop_column('services', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_column('salons', 'end_working_time')
    op.drop_column('salons', 'start_working_time')
    # ### end Alembic commands ###
