"""Change staff and service

Revision ID: b4c3d3327993
Revises: b7312924b7e5
Create Date: 2025-10-20 09:26:20.852775

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b4c3d3327993'
down_revision = 'b7312924b7e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('salon_id', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('duration', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'salons', ['salon_id'], ['id'])
    op.add_column('staffs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'staffs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staffs', type_='foreignkey')
    op.drop_column('staffs', 'user_id')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'duration')
    op.drop_column('services', 'salon_id')
    # ### end Alembic commands ###
