"""Add user phone_number

Revision ID: b7312924b7e5
Revises: 029e0ebe96de
Create Date: 2025-10-13 10:27:39.935029

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b7312924b7e5'
down_revision = '029e0ebe96de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.alter_column('appointments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    # Add constraint to ensure either user_id or phone_number is present
    op.create_check_constraint(
        'check_user_or_phone',
        'appointments',
        '(user_id IS NOT NULL) OR (phone_number IS NOT NULL)'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop constraint first
    op.drop_constraint('check_user_or_phone', 'appointments', type_='check')
    
    # op.add_column('services', sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.alter_column('appointments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('appointments', 'phone_number')
    # ### end Alembic commands ###
